apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:vsRWzS1Cw3aHJmp3jMREOEku98AdJKHvsxw0DeEFpA89ffMn3H3wwkVQzZDPjOJaK8+0M/XiVsE=,iv:41LrXjRUct4/+FpRLo/+LsjMW9q+TM/XJMQod1D72A4=,tag:T7PpvQ6JrQJufcpygP1P3g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cf
    namespace: cert-manager
sops:
    age:
        - recipient: age1xcavq2xfqzvr6jr0amr2axjgjrn70v5fd9gs8mpu7yzvc297pucscxd252
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbkJDd2lUSHc1NUNlVkhV
            RnZNMTZSdGg4bTlIUTg1Mko0bjBqWVhST1dzCll0UGpNU0JSZ2YwUVREN0RBM2k5
            UnU2SFdDR2FzenRHSkpub3FJazNSODQKLS0tIHQxOWNkNDBoQ2ozN1hOVnpxUElD
            NCsvbXhQbGY0L29FZ25KMWRTS0lNclkKzKvH1pJllqSnO6NcGpXTJPr2y3HmZioZ
            sMneY54zIaYeBnmnZlTPgtN9SLBxnh6BHpuj/ctSmr13FzRIX3URLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-01T14:20:32Z"
    mac: ENC[AES256_GCM,data:9b1HyVoZNvWRwSOoyZPuNYW/dAcrWsFGCrOpARH2+4sMcq2v45U/O+l9nQ0oknh13lcKNaRinDaREEwZ6CN6PgNip2ZJwmpFSPQLbUWeXSTcI3CZlXwCg3AIzox6xum/DCNX+emNe3xIGU3MigQT4Epcj+6BU0zedl9jisUmBms=,iv:UXdPD9pIOBWzjmNzQ1daqIDKtrfyx7vj3EFIQ68DcPs=,tag:zJOhN04AFK8QAn1calWzUg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
