apiVersion: v1
data:
    token: ENC[AES256_GCM,data:Th7tuImshgxNUfZHKmgxetSRUJCo41cyCeTf8Zaaqx4X6E4cteitGVUWYT1mp8SxFjRMABq3777F0d6QkzhCSiF/qt59eIbtYJKApe06rudd5TpralsWq0xneOEdWX2uvQr1h2Ore2799MNHdtDYLDhM3oyaUnUku9fOEb4y7vyeU5Af1D+Gr1LpgZ0NLhLhuljpaXENjjcIH0fKD8WW0+0re5VB4YWAb8iO70hwHxd0s90mdX1s4UnESu6XI10kkmT/XsTXKqleW4fvp4UhHyBYa98HhGL1QUMynetnUyWYnbF9jxRnt+nnbADqw6JCK0OHHL9yWxQ=,iv:vBOKqFfFrBZvTSanxOQp5y3diMREpbZJ2O//YzzaNlQ=,tag:qwHX/kNcaSRjgZOMqOOrjA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cloudflared
    namespace: cloudflared
sops:
    age:
        - recipient: age1xcavq2xfqzvr6jr0amr2axjgjrn70v5fd9gs8mpu7yzvc297pucscxd252
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabnlOdTQxTTZNQlYxMkVt
            NmhHZE1EREphSWN6M09CR0ZlMkw2K3BNNGxzCitzUWhaQWtBcUVTa2ZyR0gzT3NU
            MmM3aXZ2WmVsRSs3N1pZRFJTd1pWZ3MKLS0tIExQVGlrQVQ4RFk5NmRQZE9XQ3Y4
            NDFjdWhVTTh1TnN4RHV0VEp3US9QTzQKh4B9TAM1rHdEcU6VOeHs3gjc6I2nZKH3
            TatTqm+oahD2e33sleCmyIWFmtnRwG/e7ArKrN1b6q0jpcV3afaXsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-14T15:14:45Z"
    mac: ENC[AES256_GCM,data:MI0osg2jKI+VBYtryZcvt9XiKicafCMvDXwKAiXoLyZ0xvLYuJDUB+C9ZrF7JrN7ya55ctKtvfMABkgJsB15nvlJnq6/FuB80DnU3+38SW7x6u5o0j+031CM4QkvaOSVAM/zWDRXdcXCeT4YfjVUPWcxEa2bwTFoTikC/4PSkEE=,iv:oq3mcB+O+cuL9h9QCi6TVFvgm7SP/gKjmS2huXPYqGc=,tag:PUvSYiApARPqek6kNIIwpg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
